# Generated by Django 4.1.5 on 2023-01-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='128x128.png', upload_to='category_images'),
        ),
    ]
