# Generated by Django 4.0.5 on 2023-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='color2',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
